# https://taskfile.dev

version: 3

vars:
  filename: mnist

tasks:
  default:
    desc: List all available tasks
    cmd: task --list-all

  br:
    desc: Build app and run
    cmds:
      - task: build
      - task: run

  build:
    desc: Build app
    cmds:
      - cmake -B ./cmake-build -S .
      - cmake --build ./cmake-build --target {{ .filename }}-viz

  download:
    desc: Download MNIST dataset
    vars:
      base_url: https://raw.githubusercontent.com/fgnt/mnist/master
      files: train-images-idx3-ubyte.gz,train-labels-idx1-ubyte.gz,t10k-images-idx3-ubyte.gz,t10k-labels-idx1-ubyte.gz
    cmds:
      - mkdir -p ./data
      - for: 
          var: files
          split: ","
        cmd: curl {{ .base_url }}/{{ .ITEM }} -o ./data/{{ .ITEM }} && gzip -d ./data/{{ .ITEM }}

  run:
    desc: Run app
    cmd: ./cmake-build/{{ .filename }}-viz
